import exerciseVisualService, {
  ExerciseMatchResult,
} from "../exerciseVisualService";
import { GeneratedExerciseData } from "./types";
import { mapMuscleGroupsToBodyParts } from "./utils";

export class AIGenerator {
  async generateSemanticMapping(
    exerciseName: string,
  ): Promise<GeneratedExerciseData | null> {
    try {
      return null;
    } catch (error) {
      return null;
    }
  }

  async generateComprehensiveExerciseData(
    exerciseName: string,
  ): Promise<GeneratedExerciseData> {

    return {
      name: exerciseName,
      description: `Custom exercise: ${exerciseName}`,
      instructions: [
        "This is a custom exercise variation",
        "Follow proper form and technique",
        "Start with appropriate resistance",
        "Control the movement",
        "Breathe properly",
        "Stop if you feel pain",
      ],
      equipment: ["body weight"],
      targetMuscles: ["full body"],
      safetyTips: [
        "Warm up before exercising",
        "Use proper form",
        "Progress gradually",
      ],
      alternatives: [],
      classification: {
        primaryMovement: "isolation",
        muscleGroup: "full-body",
        equipment: "bodyweight",
        intensity: "moderate",
      },
    };
  }

  async generateExerciseData(
    exerciseName: string,
    classifyExercise: (name: string) => any,
  ): Promise<ExerciseMatchResult> {
    try {
      const generatedData =
        await this.generateComprehensiveExerciseData(exerciseName);
      const classification = classifyExercise(exerciseName);

      let visualExercise = null;
      if (generatedData.alternatives.length > 0) {
        for (const alt of generatedData.alternatives) {
          const match = await exerciseVisualService.findExercise(
            alt,
            false,
            true,
          );
          if (match) {
            visualExercise = match.exercise;
            break;
          }
        }
      }

      if (!visualExercise && classification) {
        const fallbackMatch = await exerciseVisualService.findExercise(
          classification.fallbackExercise,
          false,
          true,
        );
        if (fallbackMatch) {
          visualExercise = fallbackMatch.exercise;
        }
      }

      return {
        exercise: visualExercise || {
          exerciseId: exerciseName.toLowerCase().replace(/\s+/g, "_"),
          name: generatedData.name,
          gifUrl: "",
          targetMuscles: generatedData.targetMuscles,
          bodyParts: mapMuscleGroupsToBodyParts(generatedData.targetMuscles),
          equipments: generatedData.equipment,
          secondaryMuscles: [],
          instructions: generatedData.instructions,
        },
        confidence: 0.8,
        matchType: "fuzzy",
      };
    } catch (error) {
      console.error(`Exercise generation failed for ${exerciseName}:`, error);

      return {
        exercise: {
          exerciseId: exerciseName.toLowerCase().replace(/\s+/g, "_"),
          name: exerciseName,
          gifUrl: "",
          targetMuscles: ["full body"],
          bodyParts: ["full body"],
          equipments: ["body weight"],
          secondaryMuscles: [],
          instructions: [
            "This is a custom exercise generated by AI.",
            "Follow proper form and technique.",
            "Start with light weight or bodyweight.",
            "Focus on controlled movements.",
            "Stop if you feel any pain or discomfort.",
          ],
        },
        confidence: 0.4,
        matchType: "partial",
      };
    }
  }
}
