export const aiToDbMappings = new Map<string, string>([
  ["push_ups", "push-up"],
  ["pushups", "push-up"],
  ["push-ups", "push-up"],
  ["jumping_jacks", "jumping jack"],
  ["mountain_climbers", "mountain climber"],
  ["mountain_climber", "mountain climber"],
  ["high_knees", "run"],
  ["butt_kicks", "run"],
  ["bodyweight_squats", "squat"],
  ["air_squats", "squat"],
  ["prisoner_squats", "squat"],
  ["wall_sits", "wall squat"],
  ["sit_ups", "sit-up"],
  ["crunches", "crunch"],
  ["bicycle_crunches", "bicycle crunch"],
  ["russian_twists", "russian twist"],
  ["dead_bugs", "dead bug"],
  ["bird_dogs", "bird dog"],
  ["glute_bridges", "glute bridge"],
  ["hip_bridges", "glute bridge"],
  ["tricep_dips", "chest dip"],
  ["chair_dips", "chest dip"],
  ["pike_push_ups", "pike push up"],
  ["diamond_push_ups", "diamond push-up"],
  ["wide_grip_push_ups", "wide-grip push-up"],

  ["dumbbell_press", "dumbbell bench press"],
  ["dumbbell_rows", "dumbbell row"],
  ["dumbbell_curls", "dumbbell curl"],
  ["dumbbell_squats", "dumbbell squat"],
  ["dumbbell_lunges", "dumbbell lunge"],
  ["barbell_squats", "barbell squat"],
  ["barbell_rows", "barbell row"],
  ["barbell_curls", "barbell curl"],
  ["kettlebell_swings", "kettlebell swing"],
  ["resistance_band_pulls", "band pull apart"],

  ["light_jogging", "run"],
  ["jogging_intervals", "run"],
  ["running_in_place", "run"],
  ["stationary_running", "run"],
  ["cardio_intervals", "run"],
  ["step_ups", "step up"],
  ["box_steps", "step up"],

  ["core_twists", "russian twist"],
  ["side_bends", "side bend"],
  ["leg_raises", "leg raise"],
  ["knee_raises", "hanging knee raise"],
  ["flutter_kicks", "flutter kick"],
  ["scissors", "flutter kick"],

  ["static_stretching", "stretching"],
  ["dynamic_stretching", "stretching"],
  ["flexibility_work", "stretching"],
  ["cool_down_stretches", "stretching"],
  ["yoga_poses", "yoga"],
  ["foam_rolling", "stretching"],
]);
