/**
 * FitAI Workers - Exercise Enrichment Loader (Workout Engine v2, Phase 6A)
 *
 * Loads exerciseEnrichment.json — the slim per-exercise movementPattern/
 * loadingType/contraindications mirror generated by
 * scripts/generate-exercise-enrichment.mjs. Mirrors exerciseDatabase.ts's
 * loading pattern (module-level cache, Cloudflare Workers reuse the isolate).
 */
import enrichmentRaw from '../data/exerciseEnrichment.json';

export type MovementPattern =
  | 'squat' | 'hinge' | 'horizontal_push' | 'vertical_push'
  | 'horizontal_pull' | 'vertical_pull' | 'lunge' | 'carry'
  | 'rotation' | 'isolation';

export type LoadingType = 'barbell' | 'dumbbell' | 'machine' | 'cable' | 'bodyweight' | 'banded';

export interface ExerciseEnrichment {
  movementPattern: MovementPattern;
  loadingType: LoadingType;
  primaryMuscles: string[];
  isBodyweight: boolean;
  isTimeBased: boolean;
  contraindications: string[];
}

let cachedEnrichment: Record<string, ExerciseEnrichment> | null = null;

export function loadExerciseEnrichment(): Record<string, ExerciseEnrichment> {
  if (cachedEnrichment) return cachedEnrichment;
  cachedEnrichment = enrichmentRaw as Record<string, ExerciseEnrichment>;
  return cachedEnrichment;
}

export function getEnrichment(exerciseId: string): ExerciseEnrichment | null {
  return loadExerciseEnrichment()[exerciseId] ?? null;
}

/**
 * Candidate exerciseIds for an AI prompt, filtered by available equipment and
 * (optionally) excluding known contraindications for the user's injuries.
 * This is the list the model is given so it can only pick real exercises —
 * previously suggest-day/generate-full-week gave it NO enumerated pool at
 * all, a live hallucination surface (see plan §6A).
 */
export function getCandidateExerciseIds(
  allExercises: Array<{ exerciseId: string; equipments: string[] }>,
  availableEquipment: string[],
  injuries: string[] = [],
): string[] {
  const equipmentSet = new Set(availableEquipment.map((e) => e.toLowerCase()));
  const injurySet = new Set(injuries.map((i) => i.toLowerCase()));
  const enrichment = loadExerciseEnrichment();

  return allExercises
    .filter((ex) => {
      // Equipment: at least one of the exercise's required equipments must
      // be available (bodyweight exercises pass regardless — "body weight"
      // is always available).
      const hasEquipment =
        ex.equipments.length === 0 ||
        ex.equipments.some((e) => equipmentSet.has(e.toLowerCase())) ||
        ex.equipments.some((e) => e.toLowerCase() === 'body weight');
      if (!hasEquipment) return false;

      if (injurySet.size === 0) return true;
      const enr = enrichment[ex.exerciseId];
      if (!enr) return true; // no enrichment data — don't exclude on a guess
      // contraindications is a small, coarse tag set ('lower_back','shoulder',
      // 'knee') — exclude only on an exact tag match against a stated injury
      // keyword, never a fuzzy/partial one (avoid over-excluding).
      return !enr.contraindications.some((c) => injurySet.has(c.replace('_', ' ')));
    })
    .map((ex) => ex.exerciseId);
}
