import { Achievement } from "./types";

export function createConsistencyAchievements(): Achievement[] {
  return [
    {
      id: "consistent_starter",
      category: "consistency",
      tier: "bronze",
      title: "Consistent Starter",
      description: "Use FitAI for 7 consecutive days",
      icon: "📅",
      color: "#CD7F32",
      requirements: [{ type: "consistency_days", target: 7 }],
      reward: { type: "fitcoins", value: 100, description: "100 FitCoins" },
    },
    {
      id: "habit_builder",
      category: "consistency",
      tier: "silver",
      title: "Habit Builder",
      description: "Use FitAI for 30 consecutive days",
      icon: "🏗️",
      color: "#C0C0C0",
      requirements: [{ type: "consistency_days", target: 30 }],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Builder Title",
      },
    },
    {
      id: "dedication_master",
      category: "consistency",
      tier: "gold",
      title: "Dedication Master",
      description: "Use FitAI for 100 consecutive days",
      icon: "💎",
      color: "#FFD700",
      requirements: [{ type: "consistency_days", target: 100 }],
      reward: {
        type: "premium_trial",
        value: 30,
        description: "30-day Premium Trial",
      },
    },
    {
      id: "lifestyle_champion",
      category: "consistency",
      tier: "legendary",
      title: "Lifestyle Champion",
      description: "Use FitAI for 365 consecutive days",
      icon: "🏆👑",
      color: "#FF6B6B",
      requirements: [{ type: "consistency_days", target: 365 }],
      reward: {
        type: "title",
        value: "Lifetime Champion",
        description: "Exclusive Lifetime Champion Title + 1000 FitCoins",
      },
    },
    {
      id: "weekly_warrior",
      category: "consistency",
      tier: "bronze",
      title: "Weekly Warrior",
      description: "Complete all weekly goals for 4 weeks",
      icon: "🗓️",
      color: "#CD7F32",
      requirements: [
        {
          type: "custom",
          target: 4,
          metadata: { goal_type: "weekly_complete" },
        },
      ],
      reward: { type: "fitcoins", value: 200, description: "200 FitCoins" },
    },
    {
      id: "monthly_master",
      category: "consistency",
      tier: "gold",
      title: "Monthly Master",
      description: "Complete all monthly goals for 3 months",
      icon: "🗓️✨",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 3,
          metadata: { goal_type: "monthly_complete" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Master Title",
      },
    },
    {
      id: "workout_rhythm",
      category: "consistency",
      tier: "silver",
      title: "Workout Rhythm",
      description: "Work out 3+ times per week for 8 weeks",
      icon: "🎵",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 8,
          metadata: { activity: "workout_3x_week" },
        },
      ],
      reward: { type: "fitcoins", value: 250, description: "250 FitCoins" },
    },
    {
      id: "nutrition_rhythm",
      category: "consistency",
      tier: "silver",
      title: "Nutrition Rhythm",
      description: "Log meals daily for 4 weeks straight",
      icon: "🍽️🎵",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 28,
          metadata: { activity: "daily_nutrition_log" },
        },
      ],
      reward: { type: "fitcoins", value: 220, description: "220 FitCoins" },
    },
    {
      id: "morning_person",
      category: "consistency",
      tier: "bronze",
      title: "Morning Person",
      description: "Check in before 9 AM for 14 days",
      icon: "🌅",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 14, metadata: { time: "morning_checkin" } },
      ],
      reward: {
        type: "fitcoins",
        value: 120,
        description: "120 FitCoins + Early Bird Theme",
      },
    },
    {
      id: "night_owl",
      category: "consistency",
      tier: "bronze",
      title: "Night Owl",
      description: "Log evening progress for 14 days",
      icon: "🦉",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 14, metadata: { time: "evening_checkin" } },
      ],
      reward: {
        type: "fitcoins",
        value: 120,
        description: "120 FitCoins + Night Theme",
      },
    },
    {
      id: "rest_master",
      category: "consistency",
      tier: "silver",
      title: "Rest Master",
      description: "Take scheduled rest days for 4 weeks",
      icon: "😴",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 4,
          metadata: { activity: "rest_days_taken" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 180,
        description: "180 FitCoins + Rest Guru Title",
      },
    },
    {
      id: "goal_getter",
      category: "consistency",
      tier: "gold",
      title: "Goal Getter",
      description: "Hit daily goals 50 times",
      icon: "🎯",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 50,
          metadata: { achievement: "daily_goals" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 350,
        description: "350 FitCoins + Target Master Title",
      },
    },
    {
      id: "perfect_week",
      category: "consistency",
      tier: "gold",
      title: "Perfect Week",
      description: "Complete a perfect week (all goals met)",
      icon: "⭐",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 1,
          metadata: { achievement: "perfect_week" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Perfect Star",
      },
    },
    {
      id: "comeback_king",
      category: "consistency",
      tier: "silver",
      title: "Comeback King",
      description: "Return after a break and maintain 14-day streak",
      icon: "🔄",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 1,
          metadata: { achievement: "comeback_streak" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Resilience Badge",
      },
    },
  ];
}

export function createSocialAchievements(): Achievement[] {
  return [
    {
      id: "social_butterfly",
      category: "social",
      tier: "bronze",
      title: "Social Butterfly",
      description: "Add your first friend",
      icon: "👥",
      color: "#CD7F32",
      requirements: [{ type: "friend_count", target: 1 }],
      reward: { type: "fitcoins", value: 50, description: "50 FitCoins" },
    },
    {
      id: "squad_leader",
      category: "social",
      tier: "silver",
      title: "Squad Leader",
      description: "Have 10 fitness friends",
      icon: "👥💪",
      color: "#C0C0C0",
      requirements: [{ type: "friend_count", target: 10 }],
      reward: {
        type: "fitcoins",
        value: 150,
        description: "150 FitCoins + Leader Badge",
      },
    },
    {
      id: "community_champion",
      category: "social",
      tier: "gold",
      title: "Community Champion",
      description: "Have 25 fitness friends",
      icon: "🏆👥",
      color: "#FFD700",
      requirements: [{ type: "friend_count", target: 25 }],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Champion Title",
      },
    },
    {
      id: "motivator",
      category: "social",
      tier: "bronze",
      title: "Motivator",
      description: "Give 10 workout kudos",
      icon: "👍",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 10, metadata: { activity: "kudos_given" } },
      ],
      reward: { type: "fitcoins", value: 60, description: "60 FitCoins" },
    },
    {
      id: "encourager",
      category: "social",
      tier: "silver",
      title: "Encourager",
      description: "Leave 25 motivational comments",
      icon: "💬",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 25,
          metadata: { activity: "comments_posted" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 125,
        description: "125 FitCoins + Encourager Badge",
      },
    },
    {
      id: "inspiration",
      category: "social",
      tier: "gold",
      title: "Inspiration",
      description: "Receive 50 workout kudos",
      icon: "✨",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 50,
          metadata: { activity: "kudos_received" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Inspiration Title",
      },
    },
    {
      id: "challenge_creator",
      category: "social",
      tier: "silver",
      title: "Challenge Creator",
      description: "Create 5 friend challenges",
      icon: "🎯",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 5,
          metadata: { activity: "challenges_created" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 150,
        description: "150 FitCoins + Creator Badge",
      },
    },
    {
      id: "workout_buddy",
      category: "social",
      tier: "bronze",
      title: "Workout Buddy",
      description: "Complete 5 workouts with friends",
      icon: "🤝💪",
      color: "#CD7F32",
      requirements: [
        {
          type: "custom",
          target: 5,
          metadata: { activity: "friend_workouts" },
        },
      ],
      reward: { type: "fitcoins", value: 100, description: "100 FitCoins" },
    },
    {
      id: "team_player",
      category: "social",
      tier: "gold",
      title: "Team Player",
      description: "Join 3 group challenges",
      icon: "⚽",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 3,
          metadata: { activity: "group_challenges" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Team Title",
      },
    },
    {
      id: "leaderboard_star",
      category: "social",
      tier: "platinum",
      title: "Leaderboard Star",
      description: "Reach #1 on weekly leaderboard",
      icon: "⭐👑",
      color: "#E5E4E2",
      requirements: [
        {
          type: "custom",
          target: 1,
          metadata: { activity: "leaderboard_first" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Star Title",
      },
    },
    {
      id: "mentor",
      category: "social",
      tier: "gold",
      title: "Mentor",
      description: "Help 10 new users with their fitness journey",
      icon: "🎓",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 10,
          metadata: { activity: "mentored_users" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Mentor Title",
      },
    },
    {
      id: "viral_star",
      category: "social",
      tier: "legendary",
      title: "Viral Star",
      description: "Get 100 likes on a workout post",
      icon: "🔥📱",
      color: "#FF6B6B",
      requirements: [
        { type: "custom", target: 100, metadata: { activity: "post_likes" } },
      ],
      reward: {
        type: "title",
        value: "Viral Sensation",
        description: "Exclusive Viral Star Title + 750 FitCoins",
      },
    },
  ];
}
