import { Achievement } from "./types";

export function createFitnessAchievements(): Achievement[] {
  return [
    {
      id: "first_workout",
      category: "fitness",
      tier: "bronze",
      title: "First Steps",
      description: "Complete your first workout with FitAI",
      icon: "🏃",
      color: "#CD7F32",
      requirements: [{ type: "workout_count", target: 1 }],
      reward: { type: "fitcoins", value: 50, description: "50 FitCoins" },
    },
    {
      id: "workout_warrior",
      category: "fitness",
      tier: "silver",
      title: "Workout Warrior",
      description: "Complete 10 workouts",
      icon: "💪",
      color: "#C0C0C0",
      requirements: [{ type: "workout_count", target: 10 }],
      reward: {
        type: "fitcoins",
        value: 100,
        description: "100 FitCoins + Warrior Title",
      },
    },
    {
      id: "fitness_champion",
      category: "fitness",
      tier: "gold",
      title: "Fitness Champion",
      description: "Complete 50 workouts",
      icon: "🏆",
      color: "#FFD700",
      requirements: [{ type: "workout_count", target: 50 }],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Champion Title",
      },
    },
    {
      id: "fitness_legend",
      category: "fitness",
      tier: "platinum",
      title: "Fitness Legend",
      description: "Complete 100 workouts",
      icon: "👑",
      color: "#E5E4E2",
      requirements: [{ type: "workout_count", target: 100 }],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Legend Title",
      },
    },
    {
      id: "calorie_crusher",
      category: "fitness",
      tier: "bronze",
      title: "Calorie Crusher",
      description: "Burn 1,000 calories total",
      icon: "🔥",
      color: "#CD7F32",
      requirements: [{ type: "calories_burned", target: 1000 }],
      reward: { type: "fitcoins", value: 75, description: "75 FitCoins" },
    },
    {
      id: "inferno_master",
      category: "fitness",
      tier: "gold",
      title: "Inferno Master",
      description: "Burn 10,000 calories total",
      icon: "🔥🔥",
      color: "#FFD700",
      requirements: [{ type: "calories_burned", target: 10000 }],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Fire Avatar",
      },
    },
    {
      id: "calorie_volcano",
      category: "fitness",
      tier: "diamond",
      title: "Calorie Volcano",
      description: "Burn 50,000 calories total",
      icon: "🌋",
      color: "#B9F2FF",
      requirements: [{ type: "calories_burned", target: 50000 }],
      reward: {
        type: "premium_trial",
        value: 7,
        description: "7-day Premium Trial",
      },
    },
    {
      id: "iron_apprentice",
      category: "fitness",
      tier: "bronze",
      title: "Iron Apprentice",
      description: "Complete 5 strength workouts",
      icon: "🏋️",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 5, metadata: { workout_type: "strength" } },
      ],
      reward: { type: "fitcoins", value: 60, description: "60 FitCoins" },
    },
    {
      id: "strength_titan",
      category: "fitness",
      tier: "platinum",
      title: "Strength Titan",
      description: "Complete 50 strength workouts",
      icon: "🦾",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 50, metadata: { workout_type: "strength" } },
      ],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Titan Theme",
      },
    },
    {
      id: "cardio_rookie",
      category: "fitness",
      tier: "bronze",
      title: "Cardio Rookie",
      description: "Complete 5 cardio workouts",
      icon: "🏃‍♂️",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 5, metadata: { workout_type: "cardio" } },
      ],
      reward: { type: "fitcoins", value: 60, description: "60 FitCoins" },
    },
    {
      id: "endurance_beast",
      category: "fitness",
      tier: "gold",
      title: "Endurance Beast",
      description: "Complete 30 cardio workouts",
      icon: "🦸",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 30, metadata: { workout_type: "cardio" } },
      ],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Beast Avatar",
      },
    },
    {
      id: "flexibility_seeker",
      category: "fitness",
      tier: "bronze",
      title: "Flexibility Seeker",
      description: "Complete 5 flexibility workouts",
      icon: "🤸",
      color: "#CD7F32",
      requirements: [
        {
          type: "custom",
          target: 5,
          metadata: { workout_type: "flexibility" },
        },
      ],
      reward: { type: "fitcoins", value: 60, description: "60 FitCoins" },
    },
    {
      id: "yoga_master",
      category: "fitness",
      tier: "gold",
      title: "Yoga Master",
      description: "Complete 25 yoga/flexibility workouts",
      icon: "🧘‍♀️",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 25,
          metadata: { workout_type: "flexibility" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Zen Theme",
      },
    },
    {
      id: "hiit_novice",
      category: "fitness",
      tier: "silver",
      title: "HIIT Novice",
      description: "Complete 5 HIIT workouts",
      icon: "⚡",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 5, metadata: { workout_type: "hiit" } },
      ],
      reward: { type: "fitcoins", value: 80, description: "80 FitCoins" },
    },
    {
      id: "hiit_destroyer",
      category: "fitness",
      tier: "platinum",
      title: "HIIT Destroyer",
      description: "Complete 30 HIIT workouts",
      icon: "⚡⚡",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 30, metadata: { workout_type: "hiit" } },
      ],
      reward: {
        type: "fitcoins",
        value: 350,
        description: "350 FitCoins + Lightning Avatar",
      },
    },
    {
      id: "early_bird",
      category: "fitness",
      tier: "silver",
      title: "Early Bird",
      description: "Complete 10 workouts before 8 AM",
      icon: "🌅",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { time_range: "before_8am" } },
      ],
      reward: {
        type: "fitcoins",
        value: 120,
        description: "120 FitCoins + Morning Theme",
      },
    },
    {
      id: "weekend_warrior",
      category: "fitness",
      tier: "bronze",
      title: "Weekend Warrior",
      description: "Complete 10 weekend workouts",
      icon: "🎯",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 10, metadata: { day_type: "weekend" } },
      ],
      reward: { type: "fitcoins", value: 90, description: "90 FitCoins" },
    },
    {
      id: "quick_session",
      category: "fitness",
      tier: "bronze",
      title: "Quick Session",
      description: "Complete 15 workouts under 20 minutes",
      icon: "⏱️",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 15, metadata: { duration: "under_20min" } },
      ],
      reward: { type: "fitcoins", value: 70, description: "70 FitCoins" },
    },
    {
      id: "endurance_marathon",
      category: "fitness",
      tier: "gold",
      title: "Endurance Marathon",
      description: "Complete 10 workouts over 60 minutes",
      icon: "🏃‍♂️💨",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 10, metadata: { duration: "over_60min" } },
      ],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Marathon Badge",
      },
    },
    {
      id: "bodyweight_master",
      category: "fitness",
      tier: "silver",
      title: "Bodyweight Master",
      description: "Complete 20 bodyweight workouts",
      icon: "🤾",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 20, metadata: { equipment: "bodyweight" } },
      ],
      reward: { type: "fitcoins", value: 150, description: "150 FitCoins" },
    },
    {
      id: "gym_beast",
      category: "fitness",
      tier: "gold",
      title: "Gym Beast",
      description: "Complete 25 gym workouts",
      icon: "🏋️‍♀️",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 25, metadata: { equipment: "full_gym" } },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Gym Theme",
      },
    },
    {
      id: "perfectionist",
      category: "fitness",
      tier: "platinum",
      title: "Perfectionist",
      description: "Complete 5 perfect workouts (100% completion)",
      icon: "💯",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 5, metadata: { completion: "100%" } },
      ],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Perfect Badge",
      },
    },
    {
      id: "workout_explorer",
      category: "fitness",
      tier: "silver",
      title: "Workout Explorer",
      description: "Try all 5 workout types",
      icon: "🗺️",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 5, metadata: { variety: "all_types" } },
      ],
      reward: {
        type: "fitcoins",
        value: 180,
        description: "180 FitCoins + Explorer Title",
      },
    },
  ];
}

export function createNutritionAchievements(): Achievement[] {
  return [
    {
      id: "nutrition_newbie",
      category: "nutrition",
      tier: "bronze",
      title: "Nutrition Newbie",
      description: "Log your first meal",
      icon: "🍎",
      color: "#CD7F32",
      requirements: [{ type: "nutrition_log", target: 1 }],
      reward: { type: "fitcoins", value: 25, description: "25 FitCoins" },
    },
    {
      id: "food_tracker",
      category: "nutrition",
      tier: "silver",
      title: "Food Tracker",
      description: "Log meals for 7 consecutive days",
      icon: "📝",
      color: "#C0C0C0",
      requirements: [{ type: "nutrition_log", target: 7, timeframe: "daily" }],
      reward: { type: "fitcoins", value: 150, description: "150 FitCoins" },
    },
    {
      id: "nutrition_master",
      category: "nutrition",
      tier: "gold",
      title: "Nutrition Master",
      description: "Log meals for 30 days",
      icon: "🏆🍽️",
      color: "#FFD700",
      requirements: [{ type: "nutrition_log", target: 30, timeframe: "daily" }],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Master Chef Title",
      },
    },
    {
      id: "hydration_hero",
      category: "nutrition",
      tier: "bronze",
      title: "Hydration Hero",
      description: "Reach daily water goal 5 times",
      icon: "💧",
      color: "#CD7F32",
      requirements: [{ type: "water_intake", target: 5 }],
      reward: { type: "fitcoins", value: 60, description: "60 FitCoins" },
    },
    {
      id: "aqua_champion",
      category: "nutrition",
      tier: "gold",
      title: "Aqua Champion",
      description: "Reach daily water goal 30 times",
      icon: "🌊",
      color: "#FFD700",
      requirements: [{ type: "water_intake", target: 30 }],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Ocean Theme",
      },
    },
    {
      id: "protein_power",
      category: "nutrition",
      tier: "silver",
      title: "Protein Power",
      description: "Hit protein goal 10 times",
      icon: "🥩",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { macro: "protein" } },
      ],
      reward: { type: "fitcoins", value: 120, description: "120 FitCoins" },
    },
    {
      id: "carb_crusher",
      category: "nutrition",
      tier: "silver",
      title: "Carb Crusher",
      description: "Hit carb goal 10 times",
      icon: "🍞",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { macro: "carbs" } },
      ],
      reward: { type: "fitcoins", value: 120, description: "120 FitCoins" },
    },
    {
      id: "fat_fighter",
      category: "nutrition",
      tier: "silver",
      title: "Fat Fighter",
      description: "Hit healthy fat goal 10 times",
      icon: "🥑",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { macro: "fat" } },
      ],
      reward: { type: "fitcoins", value: 120, description: "120 FitCoins" },
    },
    {
      id: "macro_master",
      category: "nutrition",
      tier: "platinum",
      title: "Macro Master",
      description: "Hit all macro goals in one day, 15 times",
      icon: "📊",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 15, metadata: { macro: "all_three" } },
      ],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Nutrition Expert Title",
      },
    },
    {
      id: "veggie_lover",
      category: "nutrition",
      tier: "bronze",
      title: "Veggie Lover",
      description: "Log 50 servings of vegetables",
      icon: "🥬",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 50, metadata: { food_type: "vegetables" } },
      ],
      reward: { type: "fitcoins", value: 80, description: "80 FitCoins" },
    },
    {
      id: "fruit_fanatic",
      category: "nutrition",
      tier: "bronze",
      title: "Fruit Fanatic",
      description: "Log 30 servings of fruit",
      icon: "🍓",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 30, metadata: { food_type: "fruits" } },
      ],
      reward: { type: "fitcoins", value: 70, description: "70 FitCoins" },
    },
    {
      id: "whole_grain_warrior",
      category: "nutrition",
      tier: "silver",
      title: "Whole Grain Warrior",
      description: "Log 25 servings of whole grains",
      icon: "🌾",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 25, metadata: { food_type: "whole_grains" } },
      ],
      reward: { type: "fitcoins", value: 100, description: "100 FitCoins" },
    },
    {
      id: "plant_based_pro",
      category: "nutrition",
      tier: "gold",
      title: "Plant-Based Pro",
      description: "Log 30 plant-based meals",
      icon: "🌱",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 30, metadata: { diet_type: "plant_based" } },
      ],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Green Theme",
      },
    },
    {
      id: "keto_king",
      category: "nutrition",
      tier: "gold",
      title: "Keto King",
      description: "Log 20 keto-friendly meals",
      icon: "🥓",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 20, metadata: { diet_type: "keto" } },
      ],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Keto Crown",
      },
    },
    {
      id: "meal_prep_rookie",
      category: "nutrition",
      tier: "bronze",
      title: "Meal Prep Rookie",
      description: "Prep meals in advance 5 times",
      icon: "🍱",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 5, metadata: { meal_type: "prepped" } },
      ],
      reward: { type: "fitcoins", value: 75, description: "75 FitCoins" },
    },
    {
      id: "prep_master",
      category: "nutrition",
      tier: "platinum",
      title: "Prep Master",
      description: "Prep meals in advance 50 times",
      icon: "👨‍🍳",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 50, metadata: { meal_type: "prepped" } },
      ],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Chef Title",
      },
    },
    {
      id: "home_chef",
      category: "nutrition",
      tier: "silver",
      title: "Home Chef",
      description: "Cook 25 meals at home",
      icon: "🍳",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 25, metadata: { meal_source: "homemade" } },
      ],
      reward: { type: "fitcoins", value: 150, description: "150 FitCoins" },
    },
    {
      id: "mindful_eater",
      category: "nutrition",
      tier: "gold",
      title: "Mindful Eater",
      description: "Complete 20 mindful eating sessions",
      icon: "🧘‍♂️🍽️",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 20, metadata: { eating_style: "mindful" } },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Mindfulness Badge",
      },
    },
    {
      id: "calorie_counter",
      category: "nutrition",
      tier: "silver",
      title: "Calorie Counter",
      description: "Stay within calorie goals for 10 days",
      icon: "🔢",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 10,
          metadata: { goal_type: "calorie_within_range" },
        },
      ],
      reward: { type: "fitcoins", value: 140, description: "140 FitCoins" },
    },
  ];
}
