import { Achievement } from "./types";

export function createMilestoneAchievements(): Achievement[] {
  return [
    {
      id: "first_week",
      category: "milestone",
      tier: "bronze",
      title: "First Week",
      description: "Complete your first week on FitAI",
      icon: "📅",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 7, metadata: { milestone: "days_active" } },
      ],
      reward: {
        type: "fitcoins",
        value: 100,
        description: "100 FitCoins + Welcome Badge",
      },
    },
    {
      id: "first_month",
      category: "milestone",
      tier: "silver",
      title: "First Month",
      description: "Complete your first month on FitAI",
      icon: "🗓️",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 30, metadata: { milestone: "days_active" } },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Monthly Member Badge",
      },
    },
    {
      id: "veteran",
      category: "milestone",
      tier: "gold",
      title: "Veteran",
      description: "Complete 6 months on FitAI",
      icon: "🏅",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 180, metadata: { milestone: "days_active" } },
      ],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Veteran Title",
      },
    },
    {
      id: "anniversary",
      category: "milestone",
      tier: "platinum",
      title: "Anniversary",
      description: "Complete your first year on FitAI",
      icon: "🎂",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 365, metadata: { milestone: "days_active" } },
      ],
      reward: {
        type: "premium_trial",
        value: 60,
        description: "60-day Premium Trial + Anniversary Badge",
      },
    },
    {
      id: "hundred_workouts",
      category: "milestone",
      tier: "gold",
      title: "Century Club",
      description: "Complete 100 workouts",
      icon: "💯",
      color: "#FFD700",
      requirements: [{ type: "workout_count", target: 100 }],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Century Title",
      },
    },
    {
      id: "thousand_calories",
      category: "milestone",
      tier: "silver",
      title: "Calorie Crusher",
      description: "Burn 1,000 calories in total",
      icon: "🔥",
      color: "#C0C0C0",
      requirements: [{ type: "calories_burned", target: 1000 }],
      reward: { type: "fitcoins", value: 150, description: "150 FitCoins" },
    },
    {
      id: "ten_thousand_calories",
      category: "milestone",
      tier: "platinum",
      title: "Inferno Master",
      description: "Burn 10,000 calories in total",
      icon: "🌋",
      color: "#E5E4E2",
      requirements: [{ type: "calories_burned", target: 10000 }],
      reward: {
        type: "fitcoins",
        value: 600,
        description: "600 FitCoins + Inferno Title",
      },
    },
    {
      id: "weight_goal_achieved",
      category: "milestone",
      tier: "legendary",
      title: "Goal Crusher",
      description: "Achieve your weight goal",
      icon: "🎯✨",
      color: "#FF6B6B",
      requirements: [{ type: "weight_goal", target: 1 }],
      reward: {
        type: "title",
        value: "Goal Crusher",
        description: "Exclusive Goal Crusher Title + 1000 FitCoins",
      },
    },
    {
      id: "half_marathon_distance",
      category: "milestone",
      tier: "gold",
      title: "Half Marathon Hero",
      description: "Walk/Run a total of 21.1km",
      icon: "🏃‍♂️",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 21100,
          metadata: { milestone: "total_distance_meters" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 350,
        description: "350 FitCoins + Runner Badge",
      },
    },
    {
      id: "marathon_distance",
      category: "milestone",
      tier: "legendary",
      title: "Marathon Legend",
      description: "Walk/Run a total of 42.2km",
      icon: "🏃‍♂️👑",
      color: "#FF6B6B",
      requirements: [
        {
          type: "custom",
          target: 42200,
          metadata: { milestone: "total_distance_meters" },
        },
      ],
      reward: {
        type: "title",
        value: "Marathon Legend",
        description: "Exclusive Marathon Legend Title + 800 FitCoins",
      },
    },
    {
      id: "strength_milestone",
      category: "milestone",
      tier: "platinum",
      title: "Strength Milestone",
      description: "Complete 50 strength training workouts",
      icon: "💪",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 50, metadata: { workout_type: "strength" } },
      ],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Strength Title",
      },
    },
    {
      id: "cardio_milestone",
      category: "milestone",
      tier: "platinum",
      title: "Cardio Milestone",
      description: "Complete 50 cardio workouts",
      icon: "❤️",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 50, metadata: { workout_type: "cardio" } },
      ],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Cardio Title",
      },
    },
    {
      id: "flexibility_milestone",
      category: "milestone",
      tier: "gold",
      title: "Flexibility Milestone",
      description: "Complete 25 flexibility/yoga sessions",
      icon: "🧘‍♀️",
      color: "#FFD700",
      requirements: [
        {
          type: "custom",
          target: 25,
          metadata: { workout_type: "flexibility" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Zen Badge",
      },
    },
    {
      id: "nutrition_milestone",
      category: "milestone",
      tier: "gold",
      title: "Nutrition Milestone",
      description: "Log 200 meals",
      icon: "🍽️",
      color: "#FFD700",
      requirements: [{ type: "nutrition_log", target: 200 }],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Nutrition Badge",
      },
    },
    {
      id: "progress_photo_milestone",
      category: "milestone",
      tier: "silver",
      title: "Progress Tracker",
      description: "Upload 10 progress photos",
      icon: "📸",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 10,
          metadata: { milestone: "progress_photos" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 120,
        description: "120 FitCoins + Tracker Badge",
      },
    },
  ];
}

export function createStreakAchievements(): Achievement[] {
  return [
    {
      id: "workout_streak_7",
      category: "streak",
      tier: "bronze",
      title: "Week Warrior",
      description: "7-day workout streak",
      icon: "🔥",
      color: "#CD7F32",
      requirements: [{ type: "workout_streak", target: 7 }],
      reward: {
        type: "fitcoins",
        value: 150,
        description: "150 FitCoins + Streak Badge",
      },
    },
    {
      id: "workout_streak_14",
      category: "streak",
      tier: "silver",
      title: "Fortnight Fighter",
      description: "14-day workout streak",
      icon: "🔥🔥",
      color: "#C0C0C0",
      requirements: [{ type: "workout_streak", target: 14 }],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Fighter Title",
      },
    },
    {
      id: "workout_streak_30",
      category: "streak",
      tier: "gold",
      title: "Monthly Machine",
      description: "30-day workout streak",
      icon: "🔥🔥🔥",
      color: "#FFD700",
      requirements: [{ type: "workout_streak", target: 30 }],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Machine Title",
      },
    },
    {
      id: "workout_streak_100",
      category: "streak",
      tier: "legendary",
      title: "Unstoppable Force",
      description: "100-day workout streak",
      icon: "⚡🔥",
      color: "#FF6B6B",
      requirements: [{ type: "workout_streak", target: 100 }],
      reward: {
        type: "title",
        value: "Unstoppable Force",
        description: "Exclusive Legendary Title + 1200 FitCoins",
      },
    },
    {
      id: "nutrition_streak_14",
      category: "streak",
      tier: "silver",
      title: "Nutrition Navigator",
      description: "14-day nutrition logging streak",
      icon: "🥗",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 14,
          metadata: { streak_type: "nutrition_log" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 180,
        description: "180 FitCoins + Navigator Badge",
      },
    },
    {
      id: "water_streak_21",
      category: "streak",
      tier: "gold",
      title: "Hydration Hero",
      description: "21-day water goal streak",
      icon: "💧",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 21, metadata: { streak_type: "water_goal" } },
      ],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Hero Badge",
      },
    },
    {
      id: "sleep_streak_14",
      category: "streak",
      tier: "silver",
      title: "Sleep Scholar",
      description: "14-day sleep goal streak",
      icon: "😴",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 14, metadata: { streak_type: "sleep_goal" } },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Scholar Badge",
      },
    },
    {
      id: "step_streak_7",
      category: "streak",
      tier: "bronze",
      title: "Step Master",
      description: "7-day step goal streak",
      icon: "👣",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 7, metadata: { streak_type: "step_goal" } },
      ],
      reward: { type: "fitcoins", value: 100, description: "100 FitCoins" },
    },
    {
      id: "perfect_week_streak",
      category: "streak",
      tier: "platinum",
      title: "Perfect Streak",
      description: "3 consecutive perfect weeks",
      icon: "⭐",
      color: "#E5E4E2",
      requirements: [
        {
          type: "custom",
          target: 3,
          metadata: { streak_type: "perfect_week" },
        },
      ],
      reward: {
        type: "fitcoins",
        value: 600,
        description: "600 FitCoins + Perfect Title",
      },
    },
    {
      id: "comeback_streak",
      category: "streak",
      tier: "gold",
      title: "Phoenix Rising",
      description: "Start a 10-day streak after breaking a long streak",
      icon: "🔥🔄",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 1, metadata: { streak_type: "comeback_10" } },
      ],
      reward: {
        type: "fitcoins",
        value: 350,
        description: "350 FitCoins + Phoenix Badge",
      },
    },
  ];
}
