export const FITNESS_GOAL_MAP: Record<string, string> = {
  "weight-loss": "weight_loss",
  "weight-gain": "muscle_gain",
  "muscle-gain": "muscle_gain",
  general_fitness: "maintenance",
  "general-fitness": "maintenance",
  strength: "strength",
  endurance: "endurance",
  flexibility: "flexibility",
  "athletic-performance": "athletic_performance",
  athletic_performance: "athletic_performance",
  weight_loss: "weight_loss",
  muscle_gain: "muscle_gain",
  maintenance: "maintenance",
};

export const EQUIPMENT_MAP: Record<string, string> = {
  dumbbells: "dumbbell",
  kettlebells: "kettlebell",
  barbells: "barbell",
  bodyweight: "body weight",
  "resistance-bands": "resistance band",
  "resistance-band": "resistance band",
  "cable-machine": "cable",
  "stationary-bike": "stationary bike",
  "pull-up-bar": "body weight",
  "yoga-mat": "body weight",
  bench: "body weight",
  treadmill: "body weight",
  "rowing-machine": "body weight",
  "body weight": "body weight",
  dumbbell: "dumbbell",
  barbell: "barbell",
  kettlebell: "kettlebell",
  band: "band",
  cable: "cable",
  machine: "machine",
  "medicine ball": "medicine ball",
  "resistance band": "resistance band",
  "stationary bike": "stationary bike",
};

export const WORKOUT_TYPE_MAP: Record<string, string> = {
  strength: "full_body",
  cardio: "cardio",
  hiit: "full_body",
  yoga: "core",
  pilates: "core",
  flexibility: "core",
  functional: "full_body",
  sports: "full_body",
  dance: "cardio",
  "martial-arts": "full_body",
  full_body: "full_body",
  upper_body: "upper_body",
  lower_body: "lower_body",
  push: "push",
  pull: "pull",
  legs: "legs",
  chest: "chest",
  back: "back",
  shoulders: "shoulders",
  arms: "arms",
  core: "core",
};
