import type { TableSchema } from "./types";

export const USER_SCHEMAS: Record<string, TableSchema> = {
  profiles: {
    tableName: "profiles",
    fields: [
      { name: "id", type: "uuid", required: true },
      { name: "email", type: "string", required: true },
      { name: "name", type: "string", required: true },
      { name: "first_name", type: "string", required: true },
      { name: "last_name", type: "string", required: true },
      {
        name: "age",
        type: "number",
        required: true,
        minValue: 13,
        maxValue: 120,
      },
      {
        name: "gender",
        type: "string",
        required: true,
        validValues: ["male", "female", "other", "prefer_not_to_say"],
      },
      {
        name: "profile_picture",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "units",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["metric", "imperial"],
      },
      {
        name: "notifications_enabled",
        type: "boolean",
        required: false,
        nullable: true,
      },
      { name: "dark_mode", type: "boolean", required: false, nullable: true },
      { name: "country", type: "string", required: false, nullable: true },
      { name: "state", type: "string", required: false, nullable: true },
      { name: "region", type: "string", required: false, nullable: true },
      { name: "wake_time", type: "string", required: false, nullable: true },
      { name: "sleep_time", type: "string", required: false, nullable: true },
      {
        name: "occupation_type",
        type: "string",
        required: false,
        nullable: true,
        validValues: [
          "desk_job",
          "light_active",
          "moderate_active",
          "heavy_labor",
          "very_active",
        ],
      },
      {
        name: "media_preference",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["animation", "human", "both"],
      },
      {
        name: "data_usage_mode",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["wifi_only", "always"],
      },
      {
        name: "subscription_tier",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["guest", "free", "premium", "enterprise"],
      },
      {
        name: "detected_climate",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "detected_ethnicity",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "ethnicity_confirmed",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "climate_confirmed",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "preferred_bmr_formula",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "resting_heart_rate",
        type: "number",
        required: false,
        nullable: true,
        minValue: 30,
        maxValue: 200,
      },
      { name: "created_at", type: "timestamp", required: true },
      { name: "updated_at", type: "timestamp", required: true },
    ],
  },
  diet_preferences: {
    tableName: "diet_preferences",
    fields: [
      { name: "id", type: "uuid", required: true },
      { name: "user_id", type: "uuid", required: true },
      {
        name: "diet_type",
        type: "string",
        required: true,
        validValues: [
          "vegetarian",
          "vegan",
          "non-veg",
          "pescatarian",
          "keto",
          "omnivore",
        ],
      },
      { name: "allergies", type: "array", required: true },
      { name: "restrictions", type: "array", required: true },
      { name: "keto_ready", type: "boolean", required: false, nullable: true },
      {
        name: "intermittent_fasting_ready",
        type: "boolean",
        required: false,
        nullable: true,
      },
      { name: "paleo_ready", type: "boolean", required: false, nullable: true },
      {
        name: "mediterranean_ready",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "low_carb_ready",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "high_protein_ready",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "breakfast_enabled",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "lunch_enabled",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "dinner_enabled",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "snacks_enabled",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "cooking_skill_level",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["beginner", "intermediate", "advanced", "not_applicable"],
      },
      {
        name: "max_prep_time_minutes",
        type: "number",
        required: false,
        nullable: true,
        minValue: 5,
        maxValue: 180,
      },
      {
        name: "budget_level",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["low", "medium", "high"],
      },
      {
        name: "drinks_enough_water",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "limits_sugary_drinks",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "eats_regular_meals",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "avoids_late_night_eating",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "controls_portion_sizes",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "reads_nutrition_labels",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "eats_processed_foods",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "eats_5_servings_fruits_veggies",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "limits_refined_sugar",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "includes_healthy_fats",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "drinks_alcohol",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "smokes_tobacco",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "drinks_coffee",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "takes_supplements",
        type: "boolean",
        required: false,
        nullable: true,
      },
      { name: "created_at", type: "timestamp", required: true },
      { name: "updated_at", type: "timestamp", required: true },
    ],
  },
};
