import type { TableSchema } from "./types";

export const REVIEW_SCHEMAS: Record<string, TableSchema> = {
  advanced_review: {
    tableName: "advanced_review",
    fields: [
      { name: "id", type: "uuid", required: true },
      { name: "user_id", type: "uuid", required: false, nullable: true },
      {
        name: "calculated_bmi",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "calculated_bmr",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "calculated_tdee",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "metabolic_age",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "daily_calories",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "daily_protein_g",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "daily_carbs_g",
        type: "number",
        required: false,
        nullable: true,
      },
      { name: "daily_fat_g", type: "number", required: false, nullable: true },
      {
        name: "daily_water_ml",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "daily_fiber_g",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "healthy_weight_min",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "healthy_weight_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "weekly_weight_loss_rate",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "estimated_timeline_weeks",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "total_calorie_deficit",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "ideal_body_fat_min",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "ideal_body_fat_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "lean_body_mass",
        type: "number",
        required: false,
        nullable: true,
      },
      { name: "fat_mass", type: "number", required: false, nullable: true },
      {
        name: "estimated_vo2_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "overall_health_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "diet_readiness_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "fitness_readiness_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "goal_realistic_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "validation_status",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["passed", "warnings", "blocked"],
      },
      {
        name: "validation_errors",
        type: "object",
        required: false,
        nullable: true,
      },
      {
        name: "validation_warnings",
        type: "object",
        required: false,
        nullable: true,
      },
      {
        name: "refeed_schedule",
        type: "object",
        required: false,
        nullable: true,
      },
      {
        name: "medical_adjustments",
        type: "array",
        required: false,
        nullable: true,
      },
      {
        name: "bmr_formula_used",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "bmr_formula_accuracy",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "bmr_formula_confidence",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      { name: "climate_used", type: "string", required: false, nullable: true },
      {
        name: "climate_tdee_modifier",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "climate_water_modifier",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "ethnicity_used",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "bmi_cutoffs_used",
        type: "object",
        required: false,
        nullable: true,
      },
      {
        name: "calculations_version",
        type: "string",
        required: false,
        nullable: true,
      },
      { name: "bmi_category", type: "string", required: false, nullable: true },
      {
        name: "bmi_health_risk",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "heart_rate_zones",
        type: "object",
        required: false,
        nullable: true,
      },
      {
        name: "vo2_max_estimate",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "vo2_max_classification",
        type: "string",
        required: false,
        nullable: true,
      },
      { name: "health_score", type: "number", required: false, nullable: true },
      { name: "health_grade", type: "string", required: false, nullable: true },
      {
        name: "detected_climate",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "detected_ethnicity",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "target_hr_fat_burn_min",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "target_hr_fat_burn_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "target_hr_cardio_min",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "target_hr_cardio_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "target_hr_peak_min",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "target_hr_peak_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "recommended_workout_frequency",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 7,
      },
      {
        name: "recommended_cardio_minutes",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "recommended_strength_sessions",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "recommended_sleep_hours",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "current_sleep_duration",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "sleep_efficiency_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "data_completeness_percentage",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "reliability_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "personalization_level",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      {
        name: "created_at",
        type: "timestamp",
        required: false,
        nullable: true,
      },
      {
        name: "updated_at",
        type: "timestamp",
        required: false,
        nullable: true,
      },
    ],
  },
};
