import type { TableSchema } from "./types";

export const BODY_SCHEMAS: Record<string, TableSchema> = {
  body_analysis: {
    tableName: "body_analysis",
    fields: [
      { name: "id", type: "uuid", required: true },
      { name: "user_id", type: "uuid", required: true },
      {
        name: "height_cm",
        type: "number",
        required: true,
        minValue: 100,
        maxValue: 250,
      },
      {
        name: "current_weight_kg",
        type: "number",
        required: true,
        minValue: 30,
        maxValue: 300,
      },
      {
        name: "target_weight_kg",
        type: "number",
        required: true,
        minValue: 30,
        maxValue: 300,
      },
      {
        name: "target_timeline_weeks",
        type: "number",
        required: false,
        nullable: true,
        minValue: 4,
        maxValue: 104,
      },
      {
        name: "body_fat_percentage",
        type: "number",
        required: false,
        nullable: true,
        minValue: 3,
        maxValue: 50,
      },
      { name: "waist_cm", type: "number", required: false, nullable: true },
      { name: "hip_cm", type: "number", required: false, nullable: true },
      { name: "chest_cm", type: "number", required: false, nullable: true },
      {
        name: "front_photo_url",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "side_photo_url",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "back_photo_url",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "ai_estimated_body_fat",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "ai_body_type",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["ectomorph", "mesomorph", "endomorph"],
      },
      {
        name: "ai_confidence_score",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 100,
      },
      { name: "medical_conditions", type: "array", required: true },
      { name: "medications", type: "array", required: false, nullable: true },
      {
        name: "physical_limitations",
        type: "array",
        required: false,
        nullable: true,
      },
      { name: "pregnancy_status", type: "boolean", required: true },
      {
        name: "pregnancy_trimester",
        type: "number",
        required: false,
        nullable: true,
      },
      { name: "breastfeeding_status", type: "boolean", required: true },
      {
        name: "stress_level",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["low", "moderate", "high"],
      },
      { name: "bmi", type: "number", required: false, nullable: true },
      { name: "bmr", type: "number", required: false, nullable: true },
      {
        name: "ideal_weight_min",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "ideal_weight_max",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "waist_hip_ratio",
        type: "number",
        required: false,
        nullable: true,
      },
      { name: "photos", type: "object", required: false, nullable: true },
      { name: "analysis", type: "object", required: false, nullable: true },
      {
        name: "body_fat_source",
        type: "string",
        required: false,
        nullable: true,
      },
      {
        name: "body_fat_measured_at",
        type: "timestamp",
        required: false,
        nullable: true,
      },
      { name: "created_at", type: "timestamp", required: true },
      { name: "updated_at", type: "timestamp", required: true },
    ],
  },
  workout_preferences: {
    tableName: "workout_preferences",
    fields: [
      { name: "id", type: "uuid", required: true },
      { name: "user_id", type: "uuid", required: true },
      {
        name: "location",
        type: "string",
        required: true,
        validValues: ["home", "gym", "both"],
      },
      { name: "equipment", type: "array", required: true },
      {
        name: "time_preference",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "intensity",
        type: "string",
        required: true,
        validValues: ["beginner", "intermediate", "advanced"],
      },
      { name: "workout_types", type: "array", required: false, nullable: true },
      { name: "primary_goals", type: "array", required: true },
      {
        name: "activity_level",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["sedentary", "light", "moderate", "active", "extreme"],
      },
      {
        name: "workout_experience_years",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 50,
      },
      {
        name: "workout_frequency_per_week",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 7,
      },
      {
        name: "can_do_pushups",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 200,
      },
      {
        name: "can_run_minutes",
        type: "number",
        required: false,
        nullable: true,
        minValue: 0,
        maxValue: 300,
      },
      {
        name: "flexibility_level",
        type: "string",
        required: false,
        nullable: true,
        validValues: ["poor", "fair", "good", "excellent"],
      },
      {
        name: "weekly_weight_loss_goal",
        type: "number",
        required: false,
        nullable: true,
      },
      {
        name: "preferred_workout_times",
        type: "array",
        required: false,
        nullable: true,
      },
      {
        name: "enjoys_cardio",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "enjoys_strength_training",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "enjoys_group_classes",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "prefers_outdoor_activities",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "needs_motivation",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "prefers_variety",
        type: "boolean",
        required: false,
        nullable: true,
      },
      {
        name: "training_years",
        type: "number",
        required: false,
        nullable: true,
      },
      { name: "created_at", type: "timestamp", required: true },
      { name: "updated_at", type: "timestamp", required: true },
    ],
  },
};
