import { Achievement } from "./types";

export function createNutritionAchievements(): Achievement[] {
  return [
    {
      id: "nutrition_newbie",
      category: "nutrition",
      tier: "bronze",
      title: "Nutrition Newbie",
      description: "Log your first meal",
      icon: "🍎",
      color: "#CD7F32",
      requirements: [{ type: "nutrition_log", target: 1 }],
      reward: { type: "fitcoins", value: 25, description: "25 FitCoins" },
    },
    {
      id: "food_tracker",
      category: "nutrition",
      tier: "silver",
      title: "Food Tracker",
      description: "Log meals for 7 consecutive days",
      icon: "📝",
      color: "#C0C0C0",
      requirements: [{ type: "nutrition_log", target: 7, timeframe: "daily" }],
      reward: { type: "fitcoins", value: 150, description: "150 FitCoins" },
    },
    {
      id: "nutrition_master",
      category: "nutrition",
      tier: "gold",
      title: "Nutrition Master",
      description: "Log meals for 30 days",
      icon: "🏆🍽️",
      color: "#FFD700",
      requirements: [{ type: "nutrition_log", target: 30, timeframe: "daily" }],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Master Chef Title",
      },
    },
    {
      id: "hydration_hero",
      category: "nutrition",
      tier: "bronze",
      title: "Hydration Hero",
      description: "Reach daily water goal 5 times",
      icon: "💧",
      color: "#CD7F32",
      requirements: [{ type: "water_intake", target: 5 }],
      reward: { type: "fitcoins", value: 60, description: "60 FitCoins" },
    },
    {
      id: "aqua_champion",
      category: "nutrition",
      tier: "gold",
      title: "Aqua Champion",
      description: "Reach daily water goal 30 times",
      icon: "🌊",
      color: "#FFD700",
      requirements: [{ type: "water_intake", target: 30 }],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Ocean Theme",
      },
    },
    {
      id: "protein_power",
      category: "nutrition",
      tier: "silver",
      title: "Protein Power",
      description: "Hit protein goal 10 times",
      icon: "🥩",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { macro: "protein" } },
      ],
      reward: { type: "fitcoins", value: 120, description: "120 FitCoins" },
    },
    {
      id: "carb_crusher",
      category: "nutrition",
      tier: "silver",
      title: "Carb Crusher",
      description: "Hit carb goal 10 times",
      icon: "🍞",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { macro: "carbs" } },
      ],
      reward: { type: "fitcoins", value: 120, description: "120 FitCoins" },
    },
    {
      id: "fat_fighter",
      category: "nutrition",
      tier: "silver",
      title: "Fat Fighter",
      description: "Hit healthy fat goal 10 times",
      icon: "🥑",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 10, metadata: { macro: "fat" } },
      ],
      reward: { type: "fitcoins", value: 120, description: "120 FitCoins" },
    },
    {
      id: "macro_master",
      category: "nutrition",
      tier: "platinum",
      title: "Macro Master",
      description: "Hit all macro goals in one day, 15 times",
      icon: "📊",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 15, metadata: { macro: "all_three" } },
      ],
      reward: {
        type: "fitcoins",
        value: 500,
        description: "500 FitCoins + Nutrition Expert Title",
      },
    },
    {
      id: "veggie_lover",
      category: "nutrition",
      tier: "bronze",
      title: "Veggie Lover",
      description: "Log 50 servings of vegetables",
      icon: "🥬",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 50, metadata: { food_type: "vegetables" } },
      ],
      reward: { type: "fitcoins", value: 80, description: "80 FitCoins" },
    },
    {
      id: "fruit_fanatic",
      category: "nutrition",
      tier: "bronze",
      title: "Fruit Fanatic",
      description: "Log 30 servings of fruit",
      icon: "🍓",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 30, metadata: { food_type: "fruits" } },
      ],
      reward: { type: "fitcoins", value: 70, description: "70 FitCoins" },
    },
    {
      id: "whole_grain_warrior",
      category: "nutrition",
      tier: "silver",
      title: "Whole Grain Warrior",
      description: "Log 25 servings of whole grains",
      icon: "🌾",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 25, metadata: { food_type: "whole_grains" } },
      ],
      reward: { type: "fitcoins", value: 100, description: "100 FitCoins" },
    },
    {
      id: "plant_based_pro",
      category: "nutrition",
      tier: "gold",
      title: "Plant-Based Pro",
      description: "Log 30 plant-based meals",
      icon: "🌱",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 30, metadata: { diet_type: "plant_based" } },
      ],
      reward: {
        type: "fitcoins",
        value: 300,
        description: "300 FitCoins + Green Theme",
      },
    },
    {
      id: "keto_king",
      category: "nutrition",
      tier: "gold",
      title: "Keto King",
      description: "Log 20 keto-friendly meals",
      icon: "🥓",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 20, metadata: { diet_type: "keto" } },
      ],
      reward: {
        type: "fitcoins",
        value: 250,
        description: "250 FitCoins + Keto Crown",
      },
    },
    {
      id: "meal_prep_rookie",
      category: "nutrition",
      tier: "bronze",
      title: "Meal Prep Rookie",
      description: "Prep meals in advance 5 times",
      icon: "🍱",
      color: "#CD7F32",
      requirements: [
        { type: "custom", target: 5, metadata: { meal_type: "prepped" } },
      ],
      reward: { type: "fitcoins", value: 75, description: "75 FitCoins" },
    },
    {
      id: "prep_master",
      category: "nutrition",
      tier: "platinum",
      title: "Prep Master",
      description: "Prep meals in advance 50 times",
      icon: "👨‍🍳",
      color: "#E5E4E2",
      requirements: [
        { type: "custom", target: 50, metadata: { meal_type: "prepped" } },
      ],
      reward: {
        type: "fitcoins",
        value: 400,
        description: "400 FitCoins + Chef Title",
      },
    },
    {
      id: "home_chef",
      category: "nutrition",
      tier: "silver",
      title: "Home Chef",
      description: "Cook 25 meals at home",
      icon: "🍳",
      color: "#C0C0C0",
      requirements: [
        { type: "custom", target: 25, metadata: { meal_source: "homemade" } },
      ],
      reward: { type: "fitcoins", value: 150, description: "150 FitCoins" },
    },
    {
      id: "mindful_eater",
      category: "nutrition",
      tier: "gold",
      title: "Mindful Eater",
      description: "Complete 20 mindful eating sessions",
      icon: "🧘‍♂️🍽️",
      color: "#FFD700",
      requirements: [
        { type: "custom", target: 20, metadata: { eating_style: "mindful" } },
      ],
      reward: {
        type: "fitcoins",
        value: 200,
        description: "200 FitCoins + Mindfulness Badge",
      },
    },
    {
      id: "calorie_counter",
      category: "nutrition",
      tier: "silver",
      title: "Calorie Counter",
      description: "Stay within calorie goals for 10 days",
      icon: "🔢",
      color: "#C0C0C0",
      requirements: [
        {
          type: "custom",
          target: 10,
          metadata: { goal_type: "calorie_within_range" },
        },
      ],
      reward: { type: "fitcoins", value: 140, description: "140 FitCoins" },
    },
  ];
}
